// =============================
// File: workoutTracker.js (autogenerated workouts supported)
// =============================

import { logWorkout, generateSupersetTemplate } from './models/workoutLogs.js';
import { fetchTemplateById } from './models/workoutTemplates.js';

let selectedTemplateId = null;
let currentUser = 'Dad';

window.addEventListener('DOMContentLoaded', async () => {
  const urlParams = new URLSearchParams(window.location.search);
  selectedTemplateId = urlParams.get('templateId');

  let template;
  if (selectedTemplateId) {
    template = await fetchTemplateById(selectedTemplateId);
  } else {
    template = await generateSupersetTemplate(currentUser);
  }

  if (!template) {
    return alert("Unable to load or generate a workout template.");
  }

  document.getElementById('workoutTitle').textContent = `${template.title} (v${template.version || 1})`;
  renderWorkoutUI(template.exercises);
});

function renderWorkoutUI(exercises) {
  const container = document.getElementById('workoutContainer');
  container.innerHTML = '';
  exercises.forEach((exercise, index) => {
    const div = document.createElement('div');
    div.innerHTML = `
      <h4>${exercise.name}</h4>
      <input type="number" id="weight-${index}" placeholder="Weight">
      <input type="number" id="reps-${index}" placeholder="Reps">
    `;
    container.appendChild(div);
  });
}

document.getElementById('completeWorkoutBtn')?.addEventListener('click', async () => {
  const performance = {};
  document.querySelectorAll('#workoutContainer > div').forEach((div, index) => {
    const name = div.querySelector('h4').textContent;
    const weight = parseFloat(div.querySelector(`#weight-${index}`).value) || 0;
    const reps = parseInt(div.querySelector(`#reps-${index}`).value) || 0;
    performance[name] = [{ weight, reps }];
  });

  await logWorkout({
    userId: currentUser,
    templateId: selectedTemplateId || 'adaptive-auto',
    completedAt: new Date().toISOString(),
    performance
  });

  alert('Workout logged successfully!');
});
